project:
  type: website
  output-dir: docs

website:
  title: "mrouin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Professional.qmd
      - Personal.qmd

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true

editor: visual

